# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colaboratory.

# Model Training
"""

# support both Python 2 and Python 3 with minimal overhead.
from __future__ import absolute_import, division, print_function

# I am an engineer. I care only about error not warning. So, let's be maverick and ignore warnings.
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.svm import LinearSVC, SVC

data=pd.read_csv('train_data_clean.csv')
tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english')
features = tfidf.fit_transform(data.clean).toarray()
labels = data['category'].astype(str)
model_ml = LinearSVC()
model_ml.fit(features, labels) # training on whole train data

# serialize vector transformer and trained model
save_vect = 'tfidf.sav'
pickle.dump(tfidf, open(save_vect, 'wb'))
save_model = 'linearsvc_model.sav'
pickle.dump(model_ml, open(save_model, 'wb'))
